FROM rust:latest

RUN apt-get update && apt-get install -y \
    wget \
    curl

RUN wget https://dist.ipfs.tech/kubo/v0.38.2/kubo_v0.38.2_linux-amd64.tar.gz
RUN tar -xvzf kubo_v0.38.2_linux-amd64.tar.gz
RUN cd kubo && bash install.sh

RUN cargo install cargo-watch
RUN cargo install sqlx-cli --no-default-features --features postgres

WORKDIR /app

COPY . .

RUN cargo build --release

EXPOSE 8000 8080 5001 4001

CMD ["sh", "start.sh"]
